### ISSUE TITLE
Bump anywidget version

### ISSUE THREAD

**Issue by giswqs** [eodaGmbH/py-maplibregl#36]
I am excited to see this package! Currently, the package pins anywidget v0.8.1. The latest version is [v0.9.7](https://pypi.org/project/anywidget/#history). If would be great to bump it to a newer version.

**Comment by giswqs** [comment]
Also, the package requires Python >=3.9. Can it support 3.8 as well?

**Comment by crazycapivara** [comment]
@giswqs Yes you are right. I will update it as soon as possible

**Comment by crazycapivara** [comment]
#43

**Comment by crazycapivara** [comment]
@giswqs anywidget is now set to >=0.9.0
I will check Python 3.8 support. Should also work :-)

**Comment by giswqs** [comment]
Awesome! Thank you very much
