### ISSUE TITLE
MapWidget to_html() method not working

### ISSUE THREAD

**Issue by giswqs** [eodaGmbH/py-maplibregl#40]
It generates the HTML file, but the data layers do not show up. 

```python
import webbrowser

from maplibre.ipywidget import MapWidget as Map
from maplibre import Layer, LayerType, MapOptions
from maplibre.sources import GeoJSONSource

vancouver_blocks = GeoJSONSource(
    data="https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json",
)

map_options = MapOptions(
    center=(-123.1256, 49.24658),
    zoom=12,
    hash=True,
    pitch=35,
)

m = Map(map_options)
m.add_layer(
    Layer(
        type=LayerType.LINE,
        source=vancouver_blocks,
        paint={"line-color": "white"},
    )
)

temp_file = "/tmp/pymaplibregl.html"

with open(temp_file, "w") as f:
    f.write(m.to_html(style="height: 800px;"))

webbrowser.open(temp_file)
```

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/4e413bde-c2cf-4780-a864-7f15fc5d5f81)

**Comment by giswqs** [comment]
I noticed that the `add_control()` method does not work either. 

```python
from maplibre.ipywidget import MapWidget as Map
from maplibre.controls import NavigationControl, FullscreenControl

m = Map()
m.add_control(NavigationControl())
m
```
![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/b0a5c882-99ac-4d14-8866-f93866d90baa)

**Comment by crazycapivara** [comment]
@giswqs In your example on top where you want to create your html output, you must import the `Map` instead of the `MapWidget`:

```python
# Replace
# from maplibre.ipywidget import MapWidget as Map
# with
from maplibre import Map
```

**Comment by giswqs** [comment]
I know using `from maplibre import Map` works for creating HTML. One issue is that for users working with Jupyter notebook, how do they export the interactive map as an HTML file?  The delimna is that you can see the interactive map, but you can export it directly to HTML unless you go back to the notebook and change `from maplibre.ipywidget import MapWidget as Map` to  `from maplibre import Map`

**Comment by crazycapivara** [comment]
Furthermore, I can reproduce your error with missing controls. Navigation control is added by default and if I add it once again, I got 2 of them :-)

![image](https://github.com/eodaGmbH/py-maplibregl/assets/12279549/adc861d4-849a-45b2-9a0a-7676f1e74bb2)

**Comment by giswqs** [comment]
> I know using `from maplibre import Map` works for creating HTML. One issue is that for users working with Jupyter notebook, how do they export the interactive map as an HTML file? The delimna is that you can see the interactive map, but you can't export it directly to HTML unless you go back to the notebook and change `from maplibre.ipywidget import MapWidget as Map` to `from maplibre import Map`

That would be great! It will make it easier to integrate maplibre with other web apps like streamlit and solara.

**Comment by crazycapivara** [comment]
@giswqs Just forgot that it already works, you just need to activate the message queue:

```python
from maplibre.ipywidget import MapWidget as Map

m = Map()
m.use_message_queue()
# ...
```

**Comment by giswqs** [comment]
Nice! It indeed works. The caveat is that `m.use_message_queue()` needs to be placed immediately after the map creatation. It won't work if placed after `m.add_layer()`.
