### ISSUE TITLE
The HTML doesn't display the exported object

### ISSUE THREAD

**Issue by ambarja** [eodaGmbH/py-maplibregl#41]
I would like to know if when exporting to an html file it can show the objects displayed as shown in the following screenshot.
I have exported as html, but I can't visualizar the object (geopandas and raster tile).

### Output in Google Colab
![image](https://github.com/eodaGmbH/py-maplibregl/assets/23284899/0fa08468-cdc1-4abe-b19c-2859d8ff620c)

### HTML output in the web browser
![image](https://github.com/eodaGmbH/py-maplibregl/assets/23284899/25481849-bbdd-4983-976b-8558e9b2f9b1)

**Comment by crazycapivara** [comment]
@ambarja You need to activate the message queue to make it work when using the `MapWidget` object:

```python
m = Map(map_options)
m.use_message_queue()
# ...

with open("app.html", "w") as f:
    f.write(m.to_html(style="height: 800px;"))
```

I will activate this by default in a future release :-)

**Comment by ambarja** [comment]
> @ambarja You need to activate the message queue to make it work when using the `MapWidget` object:
> 
> ```python
> m = Map(map_options)
> m.use_message_queue()
> # ...
> 
> with open("app.html", "w") as f:
>     f.write(m.to_html(style="height: 800px;"))
> ```
> 
> I will activate this by default in a future release :-)
@crazycapivara 
I have been used this code, but the result is the same :c
### Google Colab 
![image](https://github.com/eodaGmbH/py-maplibregl/assets/23284899/a8c069f1-326a-437e-8f54-59892ba77110)

#### Web Browser
![Uploading image.png…]()

**Comment by crazycapivara** [comment]
You have to do this directly after initializing the map, otherwise it will not work!

**Comment by ambarja** [comment]
> You have to do this directly after initializing the map, otherwise it will not work!

please Is possible to share an example ?

**Comment by ambarja** [comment]
@crazycapivara  thank you very much for the support!
🚀 ❤️
