### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by diehl** [eodaGmbH/py-maplibregl#46]
On [this page](https://eodagmbh.github.io/py-maplibregl/layers/), in the first sentence
```
The paint and layout properties for the layers depend on the [type](https://eodagmbh.github.io/api/layer/#pymaplibregl.LayerType) of the layer.
```
the link bound to the word 'type' generates a 404 error.

**Comment by crazycapivara** [comment]
Thanks for the hint. Just fixed it.
