### ISSUE TITLE
Available Projections?

### ISSUE THREAD

**Issue by diehl** [eodaGmbH/py-maplibregl#54]
Hi Stefan, 

If memory serves, Deck.GL only supports rendering maps in EPSG:4326 (WGS84). Is this library similarly constrained? I could not seem to get a basemap to render in another projection. 

Chris

**Comment by crazycapivara** [comment]
Yes, MapLibre GL only supports  Web Mercator (EPSG:3857) projection.

btw if you want to mix Deck.GL and MapLibre layers, this is now possible in the latest version:

- https://eodagmbh.github.io/py-maplibregl/deckgl/
- https://eodagmbh.github.io/py-maplibregl/examples/deckgl_layer/
- https://eodagmbh.github.io/py-maplibregl/examples/deckgl_multiple_layers/

**Comment by diehl** [comment]
Hi Stefan, 

I appreciate the clarification! And that is awesome news about mixing Deck.GL and MapLibre layers!
