### ISSUE TITLE
PMTiles Support?

### ISSUE THREAD

**Issue by diehl** [eodaGmbH/py-maplibregl#55]
Hi Stefan, 

Is it possible by chance to use PMTiles to load a basemap? I found this webpage that discusses how to load PMTiles using the MapLibre JS library: https://docs.protomaps.com/pmtiles/maplibre

Chris

**Comment by giswqs** [comment]
I am also very interested in the PMTiles support.

What is the procedure to add support for the Maplibre plugins?
https://maplibre.org/maplibre-gl-js/docs/plugins/

**Comment by crazycapivara** [comment]
Hi Chris,

yep, this is an interesting feature. I think it should be easy to add. I will take a look at it.

**Comment by crazycapivara** [comment]
> I am also very interested in the PMTiles support.
> 
> What is the procedure to add support for the Maplibre plugins? https://maplibre.org/maplibre-gl-js/docs/plugins/

It depends on the plugin, there is no standard procedure yet.

**Comment by giswqs** [comment]
It would be great to add support for the pmtiles plugin. We can then learn from your PR to add support for other plugins.

Other useful plugins include terra-draw and mapbox-gl-draw. 
https://github.com/JamesLMilner/terra-draw
https://github.com/mapbox/mapbox-gl-draw

**Comment by diehl** [comment]
> Hi Chris,
> 
> yep, this is an interesting feature. I think it should be easy to add. I will take a look at it.

Brilliant - thank you Stefan! This would be a huge win.
