### ISSUE TITLE
Get map center, zoom level, and bounds programmatically

### ISSUE THREAD

**Issue by giswqs** [eodaGmbH/py-maplibregl#57]
It would be great to add support for getting the map center, zoom level, and bounds programmatically. For now, we can only get the mouse clicked location. Getting map center and bounds would be very useful for some computing workflows. 

Ideally, we want to use the draw control to draw some shapes and return the drawn geometries programmatically.

**Comment by crazycapivara** [comment]
Do you want to get this values on the mouse clicked event or by calling a separate function that triggers the values to be returned?

**Comment by giswqs** [comment]
Can we make them as the map attributes, similar to ipyleaflet?

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/7f10fb55-2c61-4594-9d5c-f24a130e124f)

**Comment by crazycapivara** [comment]
Yes, this is how I will make it available. The question just was, when to update these values, but I think it will be on_zoom and on_map_move :-)
