### ISSUE TITLE
Map.add_popup method not working

### ISSUE THREAD

**Issue by giswqs** [eodaGmbH/py-maplibregl#63]
The MapLibre JS does not seem to have the `addPopup` method. Ideally, the `add_popup()` method should accept lon/lat coordinates and HTML string to be displayed on the popup, similar to the JS functionality. 

```python
self.add_call("addPopup", layer_id, prop, template)
```
https://maplibre.org/maplibre-gl-js/docs/examples/popup/

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/5032b118-3b3f-4270-aaa8-b56df1b8b4dd)

**Comment by crazycapivara** [comment]
I do not know what's the usecase for this, but I can add it if needed as `Map.add_popup2` :-)

**Comment by giswqs** [comment]
It works now with this. Not sure why it didn't work earlier. 

```python
url = "https://github.com/opengeos/datasets/releases/download/world/world_cities.geojson"
geojson = requests.get(url).json()
source = {
    "type": "geojson",
    "data": geojson
}

layer = {
    "id": "cities",
    "type": "symbol",
    "source": "point",
    "layout": {
        "icon-image": "marker_15",
        "icon-size": 1,
    },
}
m.add_source("point", source)
m.add_layer(layer)
m.add_popup("cities")
```

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/a2a795c9-e2d3-4b79-8fe2-e29f77da7727)
