### ISSUE TITLE
Add Layer Controls 

### ISSUE THREAD

**Issue by Martenz** [eodaGmbH/py-maplibregl#69]
It would be nice to have also a layer list control that can be added. Like leaflet Layer Groups / Layer Controls in order to control layer visibility in case of multiple layer added to the map.

**Comment by crazycapivara** [comment]
Yep, this is really useful. For some reason MapLibre does not ship with such a control by default but I will add a custom one.

**Comment by crazycapivara** [comment]
Yep, that's how it works. If you want pure Python you need to use `Map.set_layout_property` in combination with a Shiny ui element or a Jupyter interaction element.

**Comment by crazycapivara** [comment]
In general you do dynamic changes with `Map.set_layout_property` and `Map.set_paint_property`. Take a look at [this example](https://eodagmbh.github.io/py-maplibregl/examples/vancouver_blocks/) using Shiny. You need to run the example in order to get the select boxes.

**Comment by giswqs** [comment]
[Leafmap](https://github.com/opengeos/leafmap/) has a widget for changing MapLibre layer opacity and color interactively.  It is not as nice as the leaflet built-in LayerControl, but it does work. 
https://leafmap.org/maplibre/color_switcher/

https://github.com/eodaGmbH/py-maplibregl/assets/5016453/ec9898ea-cb03-4e20-bb2f-c82ea1e77067

**Comment by giswqs** [comment]
The [PMTiles Viewer](https://pmtiles.io/?url=https%3A%2F%2Fdata.source.coop%2Fprotomaps%2Fopenstreetmap%2Ftiles%2Fv3.pmtiles#map=4.96/36.6/-101.77) has a layer control for changing layer visibility. It is a good example. 

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/59c81fe5-5c47-41e9-83c5-9d3f538f1234)
