### ISSUE TITLE
Add Draw plugin 

### ISSUE THREAD

**Issue by Martenz** [eodaGmbH/py-maplibregl#76]
Wondering if it can be possible to add also plugins, like draw tools eg:

* https://github.com/mapbox/mapbox-gl-draw
* https://github.com/JamesLMilner/terra-draw

**Comment by giswqs** [comment]
The mapbox draw plugin is already supported 

https://eodagmbh.github.io/py-maplibregl/examples/mapbox_draw_plugin/

**Comment by Martenz** [comment]
Sorry I reply myself .. I guess it is already there:

https://eodagmbh.github.io/py-maplibregl/examples/mapbox_draw_plugin/

and example here

https://eodagmbh.github.io/py-maplibregl/examples/mapbox_draw_plugin/
