### ISSUE TITLE
to_html() prints unnecessary package installation path

### ISSUE THREAD

**Issue by giswqs** [eodaGmbH/py-maplibregl#80]
When using the `to_html()` method, it prints the maplibre package installation path twice, which can probably be removed completely. 

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/9243d25c-4e39-4e45-920d-6f6aec9a9ce7)

**Comment by crazycapivara** [comment]
Yep, I also recognized this when working on a save func. So this be removed in the next release :-)
